
branches:
  only:
    - master

os: Visual Studio 2015

clone_folder: c:\projects\rtabmap

platform: x64
configuration: Release

init:
  - cmake --version
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

install:
  # Qt
  - set QTDIR=C:\Qt\5.8\msvc2015_64
  # make sure Qt bin path is before cmake bin path to avoid copying qt5 dlls from cmake before qt installation
  - set PATH=%QTDIR%\bin;%PATH%
  # Openni2
  - ps: wget 'https://dl.dropboxusercontent.com/s/d98jv79l6oy9fxz/OpenNI2.exe?dl=0' -outfile OpenNI2.exe
  - cmd: OpenNI2.exe -o"C:\Program Files" -y
  - ECHO "Installed OpenNI2:"
  - ps: "ls \"C:/Program Files/OpenNI2\""
  - set PATH=%PATH%;C:\Program Files\OpenNI2\Redist
  - set OPENNI2_INCLUDE64=C:\Program Files\OpenNI2\Include
  - set OPENNI2_LIB64=C:\Program Files\OpenNI2\Lib
  - set OPENNI2_REDIST64=C:\Program Files\OpenNI2\Redist
  # OpenCV
  - ps: wget 'http://kent.dl.sourceforge.net/project/opencvlibrary/opencv-win/3.3.1/opencv-3.3.1-vc14.exe' -outfile opencv-3.3.1-vc14.exe
  - cmd: opencv-3.3.1-vc14.exe -o"C:\Program Files" -y
  - ECHO "Installed OpenCV:"
  - ps: "ls \"C:/Program Files/opencv/build\""
  - set PATH=%PATH%;C:\Program Files\opencv\build\x64\vc14\bin
  # PCL (including QVTK)
  - ps: wget 'https://dl.dropboxusercontent.com/s/atf4r8kb1xyc1ls/PCL%201.8.1.exe?dl=0' -outfile PCL_1.8.1.exe
  - cmd: PCL_1.8.1.exe -o"C:\Program Files" -y
  - ECHO "Installed PCL:"
  - ps: "ls \"C:/Program Files/PCL 1.8.1\""
  - set PATH=%PATH%;C:\Program Files\PCL 1.8.1\bin
  # zlib
  - ps: wget 'https://docs.google.com/uc?authuser=0&id=0B46akLGdg-uaYm9MTTI4MUtUcmc&export=download' -outfile zlib-1.2.8-vc2010-x64.zip
  - ps: Expand-Archive zlib-1.2.8-vc2010-x64.zip -DestinationPath 'C:\Program Files'
  - ECHO "Installed zlib:"
  - ps: "ls \"C:/Program Files/zlib\""
  - set PATH=%PATH%;C:\Program Files\zlib\bin
  
before_build:
  - cd c:\projects\rtabmap\build
  - ECHO %PROGRAMFILES%
  - ECHO %PATH%
  - cmake -G "Visual Studio 14 2015 Win64" -DOpenCV_DIR="C:\Program Files\opencv\build" -DPCL_DIR="C:\Program Files\PCL 1.8.1\cmake" -DZLIB_ROOT="C:\Program Files\zlib" ..
  
after_build :
  - cmake --build . --config Release --target package

artifacts:
  - path: build\RTABMap-*
  
notifications:
  - provider: Email
    to:
      - matlabbe@email.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
