sudo: true
language: cpp
group: deprecated-2017Q3

compiler:
  - gcc

matrix:
  include:

    - dist: trusty
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-indigo-rtabmap-ros
        - sudo apt-get -y remove ros-indigo-rtabmap

      script: 
        - source /opt/ros/indigo/setup.bash
        - mkdir -p build && cd build
        - cmake .. 
        - make

    - dist: xenial
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-kinetic-rtabmap-ros
        - sudo apt-get -y remove ros-kinetic-rtabmap

      script: 
        - source /opt/ros/kinetic/setup.bash
        - mkdir -p build && cd build
        - cmake .. 
        - make

    - dist: bionic
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-melodic-rtabmap-ros
        - sudo apt-get -y remove ros-melodic-rtabmap

      script: 
        - source /opt/ros/melodic/setup.bash
        - mkdir -p build && cd build
        - cmake .. 
        - make

notifications:
  email:
    - matlabbe@gmail.com
