language: cpp
   
jobs:
  include:
#    - name: osx
#      compiler: clang
#      os: osx
#      install:
#        - brew install sqlite
#        - brew install pcl
#        - brew install opencv@3
    
    - name: linux-trusty
      compiler: gcc
      os: linux
      dist: trusty
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-indigo-rtabmap-ros
        - sudo apt-get -y remove ros-indigo-rtabmap

      before_script: 
        - source /opt/ros/indigo/setup.bash

    - name: linux-xenial
      compiler: gcc
      os: linux
      dist: xenial
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-kinetic-rtabmap-ros
        - sudo apt-get -y remove ros-kinetic-rtabmap

      before_script: 
        - source /opt/ros/kinetic/setup.bash

    - name: linux-bionic
      compiler: gcc
      os: linux
      dist: bionic
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-melodic-rtabmap-ros
        - sudo apt-get -y remove ros-melodic-rtabmap

      before_script: 
        - source /opt/ros/melodic/setup.bash

    - name: linux-focal
      compiler: gcc
      os: linux
      dist: focal
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-noetic-rtabmap-ros
        - sudo apt-get -y remove ros-noetic-rtabmap

      before_script: 
        - source /opt/ros/noetic/setup.bash

script:
  - mkdir -p build && cd build
  - cmake .. 
  - make

notifications:
  email:
    - matlabbe@gmail.com
